version: "3.9"
services:
  # web:
  #   build: data-access
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./database:/database
  db:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gkarina_root_password
      MYSQL_DATABASE: my_best_database
      MYSQL_USER: gkarina
      MYSQL_PASSWORD: gkarina_user_password
